name: My-Action
on:
  push:
    branches: [ main ]
jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: inst
      run: sudo apt install cmake g++ lcov
    - name: build
      run: |
        cmake . -DBUILD_TESTS=ON -DCOVERALLS=ON
        cmake —build .
        cmake —build . -t test -ARGS=--verbose
        cd ..
    - name: coverage
      run: |
        mkdir coverage
        lcov -d . -t bank_tests -o coverage/lcov.info -b . -c —no-external
        lcov —remove coverage/lcov.info '*/gtest/*' '*/gmock/*' '*/include/*' -o coverage/lcov.info
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
