name: My-Action

on:
  push:
    branches: [ main ]
jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: inst
        run: |
          sudo apt install g++ cmake lcov
          git submodule add https://github.com/google/googletest
      - name: build-run-test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: run-test
        run: ./build/lib_test
      - name: info
        run: |
          mkdir coverage
          cd coverage
          lcov -t "test" -o lcov.info -c -d ../build/bank/CMakeFiles/banking.dir 
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
